taxiexpress-master/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :drivers
  resources :cars
  resources :clients
  root 'home#index'
  
  get '/servicio', to: 'home#servicio'
  get '/contacto', to: 'home#contacto'
  get '/pedir', to: 'home#pedir'
  get '/tarifa', to: 'home#tarifa'
  

end

taxiexpress-master/app/models/car.rb
class Car < ActiveRecord::Base
    has_many :driver
  
end

taxiexpress-master/app/models/client.rb
class Client < ActiveRecord::Base
end

taxiexpress-master/app/models/driver.rb
class Driver < ActiveRecord::Base
  belongs_to :car
  def auto_placa   
    self.car.Placa 
  end
end

taxiexpress-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

taxiexpress-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  
end

taxiexpress-master/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end
  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end
  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:Marca, :Modelo, :Anio, :Placa)
    end
end

taxiexpress-master/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end
  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:Nombre, :Apellido, :DNI, :Telefono, :Direccion, :Correo, :Usuario, :Contrasenia)
    end
end

taxiexpress-master/app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
   
  
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:Nombre, :Apellido, :DNI, :Direccion, :Telefono, :auto_id)
    end
end

taxiexpress-master/app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'application'
  
  def index
  end
  
  def contacto
  end
      
      
      
  
  def servicio
  end
  
  def pedir
  end
  
  def tarifa
  end
end

taxiexpress-master/app/helpers/application_helper.rb
module ApplicationHelper
end

taxiexpress-master/app/helpers/cars_helper.rb
module CarsHelper
end

taxiexpress-master/app/helpers/clients_helper.rb
module ClientsHelper
end

taxiexpress-master/app/helpers/drivers_helper.rb
module DriversHelper
end

taxiexpress-master/app/helpers/home_helper.rb
module HomeHelper
end

taxiexpress-master/app/views/cars/_form.html.erb
<%= simple_form_for @car, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :Marca %>
  <%= error_span(@car[:Marca]) %>
  <%= f.input :Modelo %>
  <%= error_span(@car[:Modelo]) %>
  <%= f.input :Anio %>
  <%= error_span(@car[:Anio]) %>
  <%= f.input :Placa %>
  <%= error_span(@car[:Placa]) %>

    
    
    
    
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cars_path, :class => 'btn btn-default' %>
<% end %>

taxiexpress-master/app/views/cars/edit.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<table width="398" height="206" border="0">
		  <tr>
		    <td width="310"><%= render :partial => 'form' %></td>
		    <td width="78">&nbsp;</td>
	      </tr>
</table>

taxiexpress-master/app/views/cars/index.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Marca) %></th>
      <th><%= model_class.human_attribute_name(:Modelo) %></th>
      <th><%= model_class.human_attribute_name(:Anio) %></th>
      <th><%= model_class.human_attribute_name(:Placa) %></th>

    
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= link_to car.id, car_path(car) %></td>
        <td><%= car.Marca %></td>
        <td><%= car.Modelo %></td>
        <td><%= car.Anio %></td>
        <td><%= car.Placa %></td>
      
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_car_path(car), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      car_path(car),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_car_path,
            :class => 'btn btn-primary' %>

taxiexpress-master/app/views/cars/new.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<table width="398" height="206" border="0">
		  <tr>
		  	
		    <td width="310"><%= render :partial => 'form' %></td>
		    <td width="78">&nbsp;</td>
	      </tr>
</table>

taxiexpress-master/app/views/cars/show.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Marca) %>:</strong></dt>
  <dd><%= @car.Marca %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Modelo) %>:</strong></dt>
  <dd><%= @car.Modelo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Anio) %>:</strong></dt>
  <dd><%= @car.Anio%></dd>
  <dt><strong><%= model_class.human_attribute_name(:Placa) %>:</strong></dt>
  <dd><%= @car.Placa %></dd>
</dl>




<%= link_to t('.Regresar', :default => t("helpers.links.back")),
              cars_path, :class => 'btn btn-default'  %>
<%= link_to t('.Editar', :default => t("helpers.links.edit")),
              edit_car_path(@car), :class => 'btn btn-default' %>
<%= link_to t('.Eliminar', :default => t("helpers.links.destroy")),
              car_path(@car),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas seguro?')) },
              :class => 'btn btn-danger' %>

taxiexpress-master/app/views/clients/_form.html.erb
<%= simple_form_for @client, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :DNI %>
  <%= error_span(@client[:DNI]) %>
  <%= f.input :Nombre %>
  <%= error_span(@client[:Nombre]) %>
  <%= f.input :Apellido %>
  <%= error_span(@client[:Apellido]) %>
  <%= f.input :Telefono %>
  <%= error_span(@client[:Telefono]) %>
  <%= f.input :Direccion %>
  <%= error_span(@client[:Direccion]) %>
  <%= f.input :Correo %>
  <%= error_span(@client[:Correo]) %>
  <%= f.input :Usuario %>
  <%= error_span(@client[:Usuario]) %>
  <%= f.input :Contrasenia %>
  <%= error_span(@client[:Contrasenia]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clients_path, :class => 'btn btn-default' %>
<% end %>

taxiexpress-master/app/views/clients/edit.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<table width="398" height="206" border="0">
		  <tr>
		    <td width="310"><%= render :partial => 'form' %></td>
		    <td width="78">&nbsp;</td>
	      </tr>
</table>

taxiexpress-master/app/views/clients/index.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <strong><th><%= model_class.human_attribute_name(:id) %></th></strong>
      <th><%= model_class.human_attribute_name(:Nombre) %></th>
      <th><%= model_class.human_attribute_name(:Apellido) %></th>
     
      <th><%= model_class.human_attribute_name(:DNI) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to client.id, client_path(client) %></td>
        <td><%= client.Nombre %></td>
        <td><%= client.Apellido %></td>
         <td><%= client.DNI %></td>
        
        <td>
          <%= link_to t('.Editar', :default => t("helpers.links.edit")),
                      edit_client_path(client), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.Eliminar', :default => t("helpers.links.destroy")),
                      client_path(client),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas Seguro?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_client_path,
            :class => 'btn btn-primary' %>

taxiexpress-master/app/views/clients/new.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<table width="398" height="206" border="0">
		  <tr>
		    <td width="310"><%= render :partial => 'form' %></td>
		    <td width="78">&nbsp;</td>
	      </tr>
</table>

taxiexpress-master/app/views/clients/show.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Nombre) %>:</strong></dt>
  <dd><%= @client.Nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Apellido) %>:</strong></dt>
  <dd><%= @client.Apellido %></dd>
  <dt><strong><%= model_class.human_attribute_name(:DNI) %>:</strong></dt>
  <dd><%= @client.DNI %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Telefono) %>:</strong></dt>
  <dd><%= @client.Telefono %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Direccion) %>:</strong></dt>
  <dd><%= @client.Direccion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Correo) %>:</strong></dt>
  <dd><%= @client.Correo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Usuario) %>:</strong></dt>
  <dd><%= @client.Usuario %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Contrasenia) %>:</strong></dt>
  <dd><%= @client.Contrasenia %></dd>
</dl>

<%= link_to t('.Regresar', :default => t("helpers.links.back")),
              clients_path, :class => 'btn btn-default'  %>
<%= link_to t('.Editar', :default => t("helpers.links.edit")),
              edit_client_path(@client), :class => 'btn btn-default' %>
<%= link_to t('.Eliminar', :default => t("helpers.links.destroy")),
              client_path(@client),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas seguro?')) },
              :class => 'btn btn-danger' %>

taxiexpress-master/app/views/drivers/_form.html.erb
<%= simple_form_for @driver, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :Nombre %>
  <%= error_span(@driver[:Nombre]) %>
  <%= f.input :Apellido %>
  <%= error_span(@driver[:Apellido]) %>
  <%= f.input :DNI %>
  <%= error_span(@driver[:DNI]) %>
  <%= f.input :Direccion %>
  <%= error_span(@driver[:Direccion]) %>
  <%= f.input :Telefono %>
  <%= error_span(@driver[:Telefono]) %>
  <%= f.association :auto %>
  <%= error_span(@driver[:auto_id]) %>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                drivers_path, :class => 'btn btn-default' %>
<% end %>

taxiexpress-master/app/views/drivers/edit.html.erb
<%- model_class = Driver -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<table width="398" height="206" border="0">
		  <tr>
		    <td width="310"><%= render :partial => 'form' %></td>
		    <td width="78">&nbsp;</td>
	      </tr>
</table>

taxiexpress-master/app/views/drivers/index.html.erb
<%- model_class = Driver -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Nombre) %></th>
      <th><%= model_class.human_attribute_name(:Apellido) %></th>
      <th><%= model_class.human_attribute_name(:DNI) %></th>
      <th><%= model_class.human_attribute_name(:auto_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= link_to driver.id, driver_path(driver) %></td>
        <td><%= driver.Nombre %></td>
        <td><%= driver.Apellido %></td>
        <td><%= driver.DNI %></td>
        <td><%= driver.auto_placa %></td>
        
        <td>
          <%= link_to t('.Editar', :default => t("helpers.links.edit")),
                      edit_driver_path(driver), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.Eliminar', :default => t("helpers.links.destroy")),
                      driver_path(driver),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas seguro?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_driver_path,
            :class => 'btn btn-primary' %>

taxiexpress-master/app/views/drivers/new.html.erb
<%- model_class = Driver -%>
<div class="page-header">
                  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<table width="398" height="206" border="0">
		  <tr>
		    <td width="310">
		        <%= render :partial => 'form' %>
		    </td>
		    <td width="78">&nbsp;</td>
	      </tr>
</table>

taxiexpress-master/app/views/drivers/show.html.erb
<%- model_class = Driver -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Nombre) %>:</strong></dt>
  <dd><%= @driver.Nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Apellido) %>:</strong></dt>
  <dd><%= @driver.Apellido %></dd>
  <dt><strong><%= model_class.human_attribute_name(:DNI) %>:</strong></dt>
  <dd><%= @driver.DNI %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Direccion) %>:</strong></dt>
  <dd><%= @driver.Direccion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Telefono) %>:</strong></dt>
  <dd><%= @driver.Telefono %></dd>
  <dt><strong><%= model_class.human_attribute_name(:auto_id) %>:</strong></dt>
  <dd><%= @driver.auto_placa %></dd>
</dl>

<%= link_to t('.Regresar', :default => t("helpers.links.back")),
              drivers_path, :class => 'btn btn-default'  %>
<%= link_to t('.Editar', :default => t("helpers.links.edit")),
              edit_driver_path(@driver), :class => 'btn btn-default' %>
<%= link_to t('.Eliminar', :default => t("helpers.links.destroy")),
              driver_path(@driver),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas seguro?')) },
              :class => 'btn btn-danger' %>

taxiexpress-master/app/views/home/contacto.html.erb
<h1>Contacto</h1>

<p>Telefono  :  511-2154600
<p>RPC       :  511-999038031</p>
<p>Correo    :  contacto@taxixpress.pe</p>
<p>Direccion :  Av. Aviacion 3427, San Borja</p>
<iframe src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ86lDZN3HBZER8oAMCkfyack&key=AIzaSyDpDeDDhYoy_zneqoN9g-q5UbKNOVSBb8E" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
<!--<p><%= link_to 'Clients' , clients_path %></p>-->

taxiexpress-master/app/views/home/index.html.erb
<h1>Taxi Xpress</h1>
<p>Seguridad en todo momento</p>
<h2>Bienvenidos a Taxi Xpress</h2>
<p> Taxi Xpress es un una empresa que brinda el servicio de transporte al público en general así como a clientes corporativos.
    Nuestra razón de ser es el cliente, buscamos ofrecer puntualidad, comodidad, y eficiencia en cada servicio que realizamos.
<h2>VISION</h2>   
<p> Ser una empresa reconocida a nivel nacional por el servicio de movilidad en la modalidad de taxi , 
cuyo sinónimo sea de eficiencia y continuo mejoramiento en la calidad de servicio que brinda, 
considerando que las mejoras a nuestras unidades contribuirá al medio ambiente.</p>

<h2>MISION</h2>   
<p> Nuestra misión es prestar un excelente servicio de movilidad tipo taxi, teniendo como principio la mejor atención al cliente,
el uso de tecnología y la motivación de nuestros colaboradores, dando a nuestros clientes un servicio eficiente, honorable, 
ético y responsable.</p>

<h2>OBJETIVOS</h2>
<p>Nuestros objetivos son:</p>
<p>. Posicionar a TAXI XPRESS en el sector empresarial al que vamos dirigidos</p>
<p>. Contar con los mejores conductores y operadores que mostraran la imagen de eficiencia de TAXIXPRESS</p>
<p>. Propiciar eficiencia para ahorrar en el costo de los servicios a los clientes</p>
</p>

taxiexpress-master/app/views/home/intranet.html.erb
<!DOCTYPE>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Free Web Templates</title>
<meta name="Keywords" content="" />
<meta name="Description" content="" />
<link href="default.css" rel="stylesheet" type="text/css" />
<style type="text/css">
body,td,th {color: #000;}
</style>
</head>
<body>
<div id="header">
	<h1><a href=<%= root_path %>><em>Taxi Xpress</em></a>	</h1>
</div>
<div style="clear:both"></div>
<div id="content"><div class="inner_copy"></div>
	<div><img src="<%= asset_path 'img4.jpg' %>" alt="" /></div>
	 <%= yield %>
	<div style="clear:both"></div>
</div>
<div id="footer">
	<div class="fleft"><p>Copyright InnovaSoft.</p></div><div class="fright"><p>&nbsp;</p></div><div class="fclear"></div><div class="fcenter"><p>&nbsp;</p></div>
</div>
</body>
</html>

taxiexpress-master/app/views/home/servicio.html.erb
<h1>Servicios</h1>

<p>Taxi Xpress le ofrece un servicio totalmente personalizado y adaptado a sus necesidades.
Contamos con tarifas y créditos corporativos. Nuestra flota es permanentemente renovada y nuestros pilotos capacitados visten uniforme. Atención 7x24.
Ademas Taxi Expressl le ofrece la mejor atencion:</p>
     <table width="450" height="130" border="0" align="right">
		  <tr>
		  	<td width="150"> </td>
		    <td width="230">
		     <ul>
				<li>Traslados al/del aeropuerto.</li>
				<li>Servicio por horas.</li>
				<li>City Tour.</li>
				<li>Servicio Courier.</li>
				<li>Servicio ejecutivo y remisse.</li>
				<li>Traslados a provincia.</li>
			 </ul>
		    	
		    </td>
	      </tr>
</table>       
	
<p>Servicio Inmediato con Atención 24 Horas
en todo Lima </p>


<!--<p><%= link_to 'Clients' , clients_path %></p>-->

taxiexpress-master/app/views/layouts/_menu.html.erb
<li><%= link_to 'Quienes Somos', root_path %></li>
<li>
        <% if current_user %>
          <%= link_to "Sing out", destroy_user_session_path, method: :delete%>
        <% else %>
          <%= link_to "Administracion", rails_admin_path %>
        <% end %>  
  
  </li>
<li><%= link_to 'Pedir Taxi' , pedir_path %></li>
<li><%= link_to 'Servicios', servicio_path %></li>

<li> <%= link_to 'Contactenos', contacto_path %></li>

taxiexpress-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>TaxiXpress - "Confianza y Seguridad"</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
         
  <p>&nbsp</p>
	<h1><a href=<%= root_path %>><em>Taxi Xpress </em></a>	</h1>
	<p class ="nvbar-text navbar-right">
	      <% if current_user %>
          Sesion de  <%= current_user.email %>
           <%= " | " %>
          <%= link_to "Consola", rails_admin_path %>
        <% else %>
          <%= link_to "", rails_admin_path %>
        <% end %> 
       </p>
    <p>&nbsp</p>
</div>

<div style="clear:both"></div>
<div id="content"><div class="inner_copy"></div>
	<div><img src="<%= asset_path 'taxixpress.jpg' %>" alt="" /></div>
	<div id="colOne">
		<div id="menu1">
			<ul>
				<%= render 'layouts/menu' %> 
			</ul>
		</div>
		<div class="margin-news">
			<h2>&nbsp;</h2>
			<p>&nbsp;</p>
		</div>
	</div>
	<div id="colTwo">
	     <%= yield %>
	</div>
	<div style="clear:both"></div>
</div>
<div id="footer">
	<div class="fleft"><p>Copyright InnovaSoft®.</p></div><div class="fright"><p>&nbsp;</p></div><div class="fclear"></div><div class="fcenter"><p>&nbsp;</p></div>
</div>
</body>
</html>